# Generated by Django 5.0.6 on 2024-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='clubmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='clubpostmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='clubpostmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='dicussionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='dicussionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='discussioncommentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='discussioncommentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='lessonthememodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='lessonthememodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='stagefilemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='stagefilemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='stagevideomodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='stagevideomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='testquestionchoicemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='testquestionchoicemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='testquestionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='testquestionmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='userlessonmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='userlessonmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='usertestanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='usertestanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='usertestresultmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='usertestresultmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='vacansymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='vacansymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
    ]
