# Generated by Django 5.0.6 on 2024-07-28 14:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemodel',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='mazmun'),
        ),
        migrations.AddField(
            model_name='stagemodel',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='mazmun'),
        ),
        migrations.AddField(
            model_name='stagemodel',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='mazmun'),
        ),
    ]
