# Generated by Django 5.0.6 on 2024-07-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_categorymodel_name_en_categorymodel_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonmodel',
            unique_together={('theme', 'type')},
        ),
    ]
