# Generated by Django 5.0.6 on 2024-07-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_stagemodel_content_en_stagemodel_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonthememodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='lessonthememodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='lessonthememodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='testquestionmodel',
            name='text_en',
            field=models.TextField(null=True, verbose_name='matn'),
        ),
        migrations.AddField(
            model_name='testquestionmodel',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='matn'),
        ),
        migrations.AddField(
            model_name='testquestionmodel',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='matn'),
        ),
    ]
