# Generated by Django 5.0.6 on 2024-07-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lessonthememodel_title_en_lessonthememodel_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonthememodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='lessonthememodel',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='lessonthememodel',
            name='title_uz',
        ),
        migrations.AddField(
            model_name='testquestionchoicemodel',
            name='text_en',
            field=models.TextField(null=True, verbose_name='matn'),
        ),
        migrations.AddField(
            model_name='testquestionchoicemodel',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='matn'),
        ),
        migrations.AddField(
            model_name='testquestionchoicemodel',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='matn'),
        ),
    ]
