# Generated by Django 5.0.6 on 2024-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_lessonmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'mahalliy'), (2, 'umumjahon')], verbose_name='turi'),
        ),
    ]
