# Generated by Django 5.0.6 on 2024-07-31 00:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_userlessonmodel_last_seen_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='clicked_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='tashrif buyurgan foydalanuvchilar'),
        ),
    ]
