# Generated by Django 5.0.6 on 2024-07-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_categorymodel_clicked_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonthememodel',
            options={'ordering': ['-users_count'], 'verbose_name': 'dars mavzusi', 'verbose_name_plural': 'dars mavzulari'},
        ),
        migrations.AddField(
            model_name='lessonthememodel',
            name='users_count',
            field=models.BigIntegerField(default=0, verbose_name='boshlagan foydalanuvchilar soni'),
        ),
        migrations.AddField(
            model_name='userlessonmodel',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tugallangan vaqti'),
        ),
        migrations.AddField(
            model_name='userlessonmodel',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='boshlangan vaqti'),
        ),
    ]
