# Generated by Django 5.0.6 on 2024-07-31 08:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_lessonthememodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacansymodel',
            name='company_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='kompaniya_nomi'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='company_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='kompaniya_nomi'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='company_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='kompaniya_nomi'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='tavsif'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='salary_en',
            field=models.CharField(max_length=255, null=True, verbose_name='maosh'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='salary_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='maosh'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='salary_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='maosh'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='vacansymodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
    ]
