# Generated by Django 5.0.6 on 2024-07-31 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_vacansymodel_company_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacansymodel',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacansy', to='course.lessonmodel', verbose_name='darslik'),
        ),
    ]
