# Generated by Django 5.0.6 on 2024-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_vacansymodel_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
        migrations.AddField(
            model_name='clubmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='sarlavha'),
        ),
    ]
