# Generated by Django 5.0.6 on 2024-07-31 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_clubmodel_title_en_clubmodel_title_ru_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_post', to='course.clubmodel', verbose_name='klub')),
                ('user', models.ManyToManyField(related_name='club_member', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': "klub a'zosi",
                'verbose_name_plural': "klub a'zolari",
            },
        ),
        migrations.DeleteModel(
            name='ClubPostModel',
        ),
    ]
