# Generated by Django 5.0.6 on 2024-07-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='newmodel',
            options={'verbose_name': 'yangilik', 'verbose_name_plural': 'yangilikar'},
        ),
        migrations.AlterModelOptions(
            name='newsviewmodel',
            options={'verbose_name': "ko'rilgan yangilik", 'verbose_name_plural': "ko'rilgan yangiliklar"},
        ),
        migrations.AlterField(
            model_name='aboutappmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='aboutappmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='advertisingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='advertisingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='contactcategorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='contactcategorymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='newsviewmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='newsviewmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='paymentcheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='paymentcheck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='quotemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='settingsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='usercontactappmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='usercontactappmodel',
            name='source',
            field=models.CharField(choices=[('mobile', 1), (2, 'landing')], max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontactappmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
    ]
