# Generated by Django 5.0.6 on 2024-07-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_aboutappmodel_caption_af_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor_id', models.UUIDField()),
                ('ip', models.GenericIPAddressField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='common.newmodel')),
            ],
            options={
                'verbose_name': 'news view',
                'verbose_name_plural': 'news viwes',
            },
        ),
    ]
