# Generated by Django 5.0.6 on 2024-07-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_faqmodel_options_alter_newmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactappmodel',
            name='source',
            field=models.CharField(choices=[(1, 'mobile'), ('landing', 2)], max_length=255),
        ),
    ]
