# Generated by Django 5.0.6 on 2024-07-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_usercontactappmodel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactappmodel',
            name='source',
            field=models.CharField(choices=[(1, 'mobile'), ('landing', 2)], max_length=255),
        ),
    ]
