# Generated by Django 5.0.6 on 2024-07-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_usercontactappmodel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactappmodel',
            name='source',
            field=models.CharField(choices=[(1, 'mobile'), (2, 'landing')], max_length=255),
        ),
    ]
