# Generated by Django 5.0.6 on 2024-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_usercontactappmodel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactappmodel',
            name='source',
            field=models.CharField(choices=[('mobile', 1), ('landing', 2)], max_length=255),
        ),
    ]
