# Generated by Django 5.0.6 on 2024-07-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='balance',
            field=models.PositiveBigIntegerField(default=50000),
        ),
    ]
