# Generated by Django 5.0.6 on 2024-07-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pro_finish_at',
            field=models.DateTimeField(null=True),
        ),
    ]
