# Generated by Django 5.0.6 on 2024-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pro_finish_at',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
