# Generated by Django 5.0.6 on 2024-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_pro_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqti'),
        ),
    ]
