# Generated by Django 5.0.6 on 2024-07-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_pro_finish_at_alter_usermodel_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='pro_finish_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
